USE [master]
GO

/****** Object:  Database [CinemaDb]    Script Date: 12/03/2019 17:21:23 ******/
CREATE DATABASE [CinemaDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CinemaDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CinemaDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CinemaDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CinemaDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CinemaDb] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CinemaDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CinemaDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CinemaDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CinemaDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CinemaDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CinemaDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [CinemaDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CinemaDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CinemaDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CinemaDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CinemaDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CinemaDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CinemaDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CinemaDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CinemaDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CinemaDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CinemaDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CinemaDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CinemaDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CinemaDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CinemaDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CinemaDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CinemaDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CinemaDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CinemaDb] SET  MULTI_USER 
GO

ALTER DATABASE [CinemaDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CinemaDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CinemaDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CinemaDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CinemaDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CinemaDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CinemaDb] SET  READ_WRITE 
GO

